---

- name: Test
  debug:
    msg: "TESTING 123 {{ role_path}}"

- name: add a host
  add_host:
    hostname: localhost
    groups:
      - seed-hosts
    ansible_connection: local
    ansible_host: localhost
#    inventory_dir: "container-pipelines/basic-spring-boot/applier/inventory"

- name: Include only files matching bastion.yaml (2.2)
  include_vars:
    dir: vars
    files_matching: seed-hosts.yml

#- name: test1
#  debug:
#    msg: "Testing : {{testvar}}"
#- name: create pipeline
#  script: create_pipeline.sh
